from decouple import config


ARANGO_USERNAME = config('ARANGO_USERNAME')
ARANGO_PASSWORD = config('ARANGO_PASSWORD')

ARANGO_TEST_USERNAME = config('ARANGO_TEST_USERNAME')
ARANGO_TEST_PASSWORD = config('ARANGO_TEST_PASSWORD')

ARANGO_HOST = config('ARANGO_HOST')
ARANGO_PORT = config('ARANGO_PORT')


